queue_rules:
  - name: default
    queue_conditions: []
    merge_conditions: []
    branch_protection_injection_mode: queue
    autoqueue: true
    merge_method: fast-forward

pull_request_rules: []
